### ISSUE TITLE
Replace Okhttp with Java 11 Http Client.

### ISSUE THREAD

**Issue by sleski** [benzwreck/wykop4j#42]
Hi, did you try to work on it? I can not manage to add post on mikroblog with attached file..

**Comment by benzwreck** [comment]
Hi there. I was tinkering a little with that but unfortunately nothing came of it. If you could share some code and tell what works, what doesn't, is it your application's issue or simply Wykop API does not want to collaborate I could help you somehow ;)

**Comment by sleski** [comment]
Hi, I tried to do it just with java 11 HttpClient, I mean not a full Wykop-SDK, but just posting on mikroblog. I did something like this: https://github.com/sleski/wykop-api2-java/blob/master/src/main/java/pl/wykop/Mikroblog.java#L39-L44 and it works. You can use it to post some text. I am able to post with image/video (when embed = url to file). But I can not post with attached file. 
I was googling/duckduckgoing how to do this with pure Java 11 and still not done. Btw. Wykop API is horrible, but you probably know it ¯\\\_(ツ)\_/¯
I was checking this urls to find some more info:

-  https://golb.hplar.ch/2019/01/java-11-http-client.html
- https://github.com/ralscha/blog2019/blob/master/java11httpclient/client/src/main/java/ch/rasc/httpclient/File.java#L69-L91
- https://urvanov.ru/2020/08/18/java-11-httpclient-multipart-form-data/ <- This is RU

Thanks for your help ;)

**Comment by benzwreck** [comment]
I tried the first answer from [here](https://stackoverflow.com/questions/46392160/java-9-httpclient-send-a-multipart-form-data-request) and it seems to work with attached file. New entry is created containing an image. Is that what you meant?

**Comment by sleski** [comment]
yes, this is exactly what I mean, but for me it does not work. Posted new entry without image:

```
MultiPartBodyPublisher publisher = new MultiPartBodyPublisher()
				.addPart("body", message)
				.addPart("adultmedia", isAdultMedia.toString())
				.addPart("test.png", path);
		HttpRequest request = HttpRequest.newBuilder()
				.uri(URI.create(urlToPost))
				.header("Content-Type", "multipart/form-data; boundary=" + publisher.getBoundary())
				.header("apisign", encrypt(stringToMd5Hash.toString()))
				.timeout(Duration.ofMinutes(1))
				.POST(publisher.build())
				.build();
```

Later will create a branch and add my try.

**Comment by benzwreck** [comment]
Try to change
```
.addPart("test.png", path);
```
into
```
.addPart("embed", path);
```
I guess it should be working fine now.

**Comment by sleski** [comment]
Works like a charm. I will close the ticket :P 
Thanks!
